---
title: "Iteration and listcols"
author: "Lu Qiu"
date: "2023-10-31"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
library(tidyverse)
library(rvest)
```


### Lists

```{r}
vec_number = 1:4
vec_char = c('my', 'name', 'is', 'Lu')

tibble(
  num = vec_number,
  chr = vec_char
)
```

```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))
l
```

```{r}
l$vec_numeric
l[[2]]
l[['summary']]
```


### Loops

```{r}
list_norms_samples = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms_samples)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }

  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```


```{r}
mean_and_sd(list_norms_samples$a)
mean_and_sd(list_norms_samples$b)
mean_and_sd(list_norms_samples$c)
mean_and_sd(list_norms_samples$d)

```


```{r}
output = vector('list', length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms_samples[[i]])
}
```


### use `map`

```{r}
output_mean_sd = map(list_norms_samples, mean_and_sd)
output_median = map(list_norms_samples, median)
output_summary = map(list_norms_samples, summary)
```


### create DF

```{r}
listcol_df =
  tibble(
    name = c('a', 'b', 'c', 'd'),
    samp = list_norms_samples
  )
```

```{r}
mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[2]])
mean_and_sd(listcol_df$samp[[3]])

map(listcol_df$samp, mean_and_sd)

listcol_df |>
  mutate(
    mean_sd = map(samp, mean_and_sd),
    median = map(samp, median)) |>
  select(name, mean_sd) |>
  unnest(mean_sd)
```

### NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
```

import function
```{r}
nsduh_import <- function(html, table_num, outcome_name) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      outcome = outcome_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}

nsduh_import(nsduh_html, 1, 'marj')
```

import data using a for loop
```{r}
table_input = list(1, 4, 5)
name_input = list('marj', 'cocaine', 'heroine')

output = vector('list', length = 3)

for (i in 1:3) {
  output[[i]] = nsduh_import(nsduh_html, table_input[[i]], name_input[[i]])
  
}

nsduh_df = bind_rows(output)
```

Try again, using maps!

```{r}
nsduh_import <- function(html, table_num) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}

nsduh_df = 
  tibble(
    name = c("marj", "cocaine", "heroin"),
    number = c(1, 4, 5)
  ) |>
  mutate(
    table = map(number, nsduh_import, html = nsduh_html)) |>
  unnest(table)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
weather_nest_df = 
  weather_df|>
  nest(df = date:tmin)
```

Can i regress 'tmax' on `tmin` for each of these...?

```{r}
central_park_df = 
  weather_nest_df |>
  pull(df) |>
  nth(1)
```

fit a linear regression for central park

```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}

weather_lm(central_park_df)
```

let's try a for loop

```{r}
input_list = weather_nest_df |> pull(df) 
output = vector("list", length = 3)

for (i in 1:3) {
  output[[i]] = weather_lm(input_list[[i]])
}


weather_nest_df |> 
  mutate(models = map(df, weather_lm))
```


